(function () {
  "use strict";
  const $ = (selector, root = document) => root.querySelector(selector);
  const state = { editing: { service: null, doctor: null, faq: null } };
  const tokenKey = "medsite_admin_token";
  const formValue = (form, name) => form.elements[name].value.trim();
  const checked = (form, name) => form.elements[name].checked;
  const message = (text, error = false) => { const node = $("[data-admin-message]"); node.textContent = text; node.className = `form-message${error ? " is-error" : ""}`; };

  function show(view) { $("[data-login]").hidden = view !== "login"; $("[data-dashboard]").hidden = view !== "dashboard"; }
  function tableMessage(tbody, text, colspan) { tbody.replaceChildren(); const row = document.createElement("tr"); const cell = document.createElement("td"); cell.colSpan = colspan; cell.className = "empty-state"; cell.textContent = text; row.append(cell); tbody.append(row); }
  function addCell(row, value) { const cell = document.createElement("td"); cell.textContent = value; row.append(cell); return cell; }
  function actionCell(row, edit, remove) { const cell = document.createElement("td"); cell.className = "table-actions"; const editButton = document.createElement("button"); editButton.className = "button button-small button-ghost"; editButton.type = "button"; editButton.textContent = "Изменить"; editButton.onclick = edit; const deleteButton = document.createElement("button"); deleteButton.className = "button button-small button-danger"; deleteButton.type = "button"; deleteButton.textContent = "Удалить"; deleteButton.onclick = remove; cell.append(editButton, deleteButton); row.append(cell); }

  async function fillData() {
    const [services, doctors, faq] = await Promise.all([api.services({ include_inactive: true }), api.doctors({ include_inactive: true }), api.faq({ include_inactive: true })]);
    const serviceItems = services.items || [], doctorItems = doctors.items || [], faqItems = faq.items || [];
    const serviceBody = $("[data-services-table]"), doctorBody = $("[data-doctors-table]"), faqBody = $("[data-faq-table]");
    if (!serviceItems.length) tableMessage(serviceBody, "Услуг нет.", 5); else { serviceBody.replaceChildren(); serviceItems.forEach((item) => { const row = document.createElement("tr"); addCell(row, item.name); addCell(row, item.price.toLocaleString("ru-RU") + " ₽"); addCell(row, `${item.duration_minutes} мин.`); addCell(row, item.is_active ? "Активна" : "Скрыта"); actionCell(row, () => editService(item), () => remove("услугу", item.id, api.deleteService)); serviceBody.append(row); }); }
    if (!doctorItems.length) tableMessage(doctorBody, "Врачей нет.", 5); else { doctorBody.replaceChildren(); doctorItems.forEach((item) => { const row = document.createElement("tr"); addCell(row, item.full_name); addCell(row, item.specialty); addCell(row, `${item.experience_years} лет`); addCell(row, item.is_active ? "Активен" : "Скрыт"); actionCell(row, () => editDoctor(item), () => remove("врача", item.id, api.deleteDoctor)); doctorBody.append(row); }); }
    if (!faqItems.length) tableMessage(faqBody, "Вопросов нет.", 4); else { faqBody.replaceChildren(); faqItems.forEach((item) => { const row = document.createElement("tr"); addCell(row, item.question); addCell(row, item.answer); addCell(row, item.is_active ? "Активен" : "Скрыт"); actionCell(row, () => editFaq(item), () => remove("вопрос", item.id, api.deleteFaq)); faqBody.append(row); }); }
    populateDoctorServices(serviceItems); loadAppointments();
  }

  function populateDoctorServices(services) { const select = $("[name=service_ids]"); select.replaceChildren(); services.forEach((item) => { const option = new Option(`${item.name} · ${item.price.toLocaleString("ru-RU")} ₽`, item.id); select.add(option); }); }
  async function remove(label, id, fn) { if (!window.confirm(`Удалить ${label}?`)) return; try { await fn(id); message(`${label[0].toUpperCase()}${label.slice(1)} удалена.`); await fillData(); } catch (_) {} }
  function resetForm(type) { const form = $(`[data-${type}-form]`); form.reset(); state.editing[type] = null; $(`[data-${type}-submit]`).textContent = `Добавить ${type === "faq" ? "вопрос" : type === "service" ? "услугу" : "врача"}`; }
  function editService(item) { const form = $("[data-service-form]"); state.editing.service = item.id; form.elements.name.value = item.name; form.elements.description.value = item.description; form.elements.price.value = item.price; form.elements.duration_minutes.value = item.duration_minutes; form.elements.is_active.checked = item.is_active; $("[data-service-submit]").textContent = "Сохранить услугу"; form.scrollIntoView({ behavior: "smooth", block: "center" }); }
  function editDoctor(item) { const form = $("[data-doctor-form]"); state.editing.doctor = item.id; ["full_name", "specialty", "bio", "photo_url", "experience_years", "work_start", "work_end", "slot_minutes"].forEach((name) => { if (form.elements[name]) form.elements[name].value = item[name] ?? ""; }); form.elements.is_active.checked = item.is_active; [...form.elements.service_ids.options].forEach((option) => { option.selected = item.service_ids.includes(Number(option.value)); }); $("[data-doctor-submit]").textContent = "Сохранить врача"; form.scrollIntoView({ behavior: "smooth", block: "center" }); }
  function editFaq(item) { const form = $("[data-faq-form]"); state.editing.faq = item.id; form.elements.question.value = item.question; form.elements.answer.value = item.answer; form.elements.sort_order.value = item.sort_order; form.elements.is_active.checked = item.is_active; $("[data-faq-submit]").textContent = "Сохранить вопрос"; form.scrollIntoView({ behavior: "smooth", block: "center" }); }

  async function loadAppointments() { const body = $("[data-appointments-table]"); try { const result = await api.appointments({ status: $("[name=appointment_status]").value }); const items = result.items || []; if (!items.length) return tableMessage(body, "Заявок нет.", 7); body.replaceChildren(); items.forEach((item) => { const row = document.createElement("tr"); addCell(row, item.id); addCell(row, new Date(item.slot_start).toLocaleString("ru-RU")); addCell(row, item.client_name); addCell(row, item.client_phone); addCell(row, item.status === "new" ? "Новая" : item.status === "confirmed" ? "Подтверждена" : "Отменена"); const statusCell = document.createElement("td"); const select = document.createElement("select"); select.className = "compact-select"; ["new", "confirmed", "cancelled"].forEach((status) => select.add(new Option(status === "new" ? "Новая" : status === "confirmed" ? "Подтверждена" : "Отменена", status))); select.value = item.status; select.onchange = async () => { try { await api.updateAppointment(item.id, { status: select.value }); message("Статус заявки обновлён."); await loadAppointments(); } catch (_) { select.value = item.status; } }; statusCell.append(select); row.append(statusCell); addCell(row, item.lead_id); body.append(row); }); } catch (_) {} }

  async function loadSeo() { const page = $("[name=seo_page]").value; try { const item = await api.seo(page); $("[name=seo_title]").value = item.title; $("[name=seo_description]").value = item.description; } catch (_) {} }
  function bindForms() {
    $("[data-login-form]").addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget; const button = $("[type=submit]", form); button.disabled = true; try { const result = await api.login({ username: formValue(form, "username"), password: formValue(form, "password") }); sessionStorage.setItem(tokenKey, result.token); show("dashboard"); await fillData(); await loadSeo(); message("Вы вошли в панель управления."); } catch (_) {} finally { button.disabled = false; } });
    $("[data-service-form]").addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget; const body = { name: formValue(form, "name"), description: formValue(form, "description"), price: Number(formValue(form, "price")), duration_minutes: Number(formValue(form, "duration_minutes")), is_active: checked(form, "is_active") }; try { if (state.editing.service) await api.updateService(state.editing.service, body); else await api.createService(body); resetForm("service"); await fillData(); message("Услуга сохранена."); } catch (_) {} });
    $("[data-doctor-form]").addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget; const body = { full_name: formValue(form, "full_name"), specialty: formValue(form, "specialty"), bio: formValue(form, "bio"), photo_url: formValue(form, "photo_url") || null, experience_years: Number(formValue(form, "experience_years") || 0), work_start: formValue(form, "work_start") || "09:00:00", work_end: formValue(form, "work_end") || "18:00:00", slot_minutes: Number(formValue(form, "slot_minutes") || 30), is_active: checked(form, "is_active"), service_ids: [...form.elements.service_ids.selectedOptions].map((option) => Number(option.value)) }; try { if (state.editing.doctor) await api.updateDoctor(state.editing.doctor, body); else await api.createDoctor(body); resetForm("doctor"); await fillData(); message("Врач сохранён."); } catch (_) {} });
    $("[data-faq-form]").addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget; const body = { question: formValue(form, "question"), answer: formValue(form, "answer"), sort_order: Number(formValue(form, "sort_order") || 0), is_active: checked(form, "is_active") }; try { if (state.editing.faq) await api.updateFaq(state.editing.faq, body); else await api.createFaq(body); resetForm("faq"); await fillData(); message("Вопрос сохранён."); } catch (_) {} });
    $("[data-seo-form]").addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget; try { await api.updateSeo(formValue(form, "seo_page"), { title: formValue(form, "seo_title"), description: formValue(form, "seo_description") }); message("SEO-настройки сохранены."); } catch (_) {} });
    $("[name=seo_page]").addEventListener("change", loadSeo); $("[name=appointment_status]").addEventListener("change", loadAppointments);
    $("[data-logout]").addEventListener("click", () => { sessionStorage.removeItem(tokenKey); show("login"); });
    ["service", "doctor", "faq"].forEach((type) => $(`[data-${type}-reset]`).addEventListener("click", () => resetForm(type)));
  }

  bindForms(); window.addEventListener("admin:unauthorized", () => { show("login"); message("Сессия истекла. Войдите снова.", true); });
  if (sessionStorage.getItem(tokenKey)) { show("dashboard"); fillData().then(loadSeo).catch(() => show("login")); } else show("login");
}());
